Repository duckdb/duckdb-web, pull requests merged in 2023-09, with the labels that each got.

#1134 Fix spelling of Google Colab
  docs/guides/python/datafusion.md
  docs/guides/python/jupyter.md
  docs/guides/python/multiple_threads.md
Labels: nit

#1247 Document %n (nanosecond) format code.
  docs/sql/functions/dateformat.md
Labels: enhancement

#1174 Highlight function names
  _config.yml
  css/docu.scss
Labels: design
