Repository duckdb/duckdb-web, pull requests merged in 2024-04, with the labels that each got.

#2713 Update sorted aggregate description.
  docs/sql/aggregates.md
Labels: functions

#2686 Document nested NULL comparison
  docs/sql/data_types/struct.md
Labels: awaiting merge

#2590 Document string option for filename configuration
  docs/data/multiple_files/overview.md
Labels: awaiting merge, new feature
